before_install: ["sudo apt-get install postgresql-contrib --no-install-recommends --yes"]
after_script:
  - "psql -U postgres -d rspec_active_record_mocker_testing -c '\\dx'"
  - "psql -c 'SELECT extname from pg_extension'"
rvm:
  - rbx-19mode
  - 2.0.0
  - 1.9.3
  - jruby-19mode
notifications:
  recipients:
    - envygeeks@gmail.com
branches:
  only:
    - master
env:
  - "DB_TYPE=mysql2 DB_USER=travis"
  - "DB_TYPE=postgresql DB_USER=postgres"
